---
# tasks file for ubuntu_prepare
# - name: Add apt proxy
#   copy:
#     dest: /etc/apt/apt.conf.d/00aptproxy
#     content: |
#       Acquire::http::Proxy "http://{{ prepare_apt_cache_server }}:3142";

- name: apt update cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - tmux
    - curl
# - python3-pip
  
# - name: Install pip packages
  
