---
- name: Install Docker
  hosts: docker
  become: true
  pre_tasks:
    - name: Create Docker folder
      ansible.builtin.file:
        path: /docker
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
  roles:
    - ubuntu_prepare
    - geerlingguy.docker
