version: "3"
services:
  bind9:
    container_name: dns
    image: 10.5.104.20:5000/ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Europe/Moscow
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./records/shebang.vsfi.local.db:/etc/bind/zones/shebang.vsfi.local.db
      - ./usr.sbin.named:/etc/apparmor.d/usr.sbin.named
    restart: always
