version: '3'  
services:
  pki:
    image: smallstep/step-ca
    environment:
      - DOCKER_STEPCA_INIT_NAME=Smallstep
      - DOCKER_STEPCA_INIT_DNS_NAMES=localhost
      - DOCKER_STEPCA_INIT_PASSWORD=qwerty
    ports:
      - "9000:9000"
    volumes:
      - step:/home/step