http:
    routers:
        http_router:
            rule: "Host(`traefik.localhost`)"
            service: allbackend
        https_router:
            rule: "Host(`traefik.localhost`)"
            service: allbackend
            tls:
                certResolver: myresolver
                options: tlsoptions
    services:
        allbackend:
            loadBalancer:
                servers:
                    - url: "http://localhost:8000/"
                    - url: "http://localhost:8001/"
           
tls:
    options:
        tlsoptions:
            minVersion: VersionTLS12